name: ci-testing-template

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Which branch you would like to use
      location:
        type: choice
        description: cid location
        options: 
        - devices
        - pc
        required: true
      cid:
        type: string
        required: true
      image:
        type: string
        description: The image you would like to use
        required: true
      os_type:
        type: string
        description: the os type
        required: true

run-name: Testing ${{ github.event.inputs.cid }} with ${{ github.event.inputs.os_type }}

jobs:
  generate_config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || 'main' }}
    - name: echo settings
      run: |
        echo "branch [${{ github.event.inputs.branch || 'main' }}]"
        echo "location [${{ github.event.inputs.location }}]"
        echo "cid [${{ github.event.inputs.cid }}]"
        echo "image [${{ github.event.inputs.image }}]"
        echo "os type [${{ github.event.inputs.os_type }}]"
    - name: convert settings to JSON
      run: |
        echo '${{ toJson(github.event.inputs) }}' > input.json
        cat input.json
    - name: set launcher
      run: |
        echo "The default launcher:"
        cat "${{ github.event.inputs.location }}/${{ github.event.inputs.cid }}/launcher"
    - name: set job
      run: |
        echo "The template job:"
        cat "${{ github.event.inputs.location }}/${{ github.event.inputs.cid }}/${{ github.event.inputs.os_type }}/tf.yaml"
