name: Deploy Checkbox Manifest to GitHub Pages

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs every Sunday at 00:00 UTC
    - cron: '0 0 * * SUN'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push the generated index.html
      pages: write    # To deploy to GitHub Pages
      id-token: write # To authenticate with GitHub Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install canonical checkbox client
        run: |
          sudo add-apt-repository ppa:checkbox-dev/beta -y
          sudo apt-get update -qq
          sudo apt-get install canonical-certification-client checkbox-provider-gpgpu -qq -y

      - name: Generate manifest.json
        run: |
          checkbox-cli expand com.canonical.certification::client-cert-desktop-24-04 -f json > full_manifest.json
          checkbox-cli expand com.canonical.certification::client-cert-desktop-24-04-automated -f json > auto_manifest.json

      - name: Generate GitHub Page (pc-full.html)
        uses: hanhsuan/ci-testing/.github/actions/manifest_select@main
        with:
          checkbox_expend: full_manifest.json

      - name: rename to pc-full.html
        run: |
          mv index.html pc-full.html

      - name: Generate GitHub Page (pc-auto.html)
        uses: hanhsuan/ci-testing/.github/actions/manifest_select@main
        with:
          checkbox_expend: auto_manifest.json

      - name: rename to pc-auto.html
        run: |
          mv index.html pc-auto.html

      - name: Create index.html for multiple page
        run: |
          echo "<a href=\"pc-auto.html">PC Auto</a>\n<a href=\"pc-full.html">PC Full</a>" > index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' # Uploads the entire current directory, which contains index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

